// examples/react-example.jsx
import { useEffect, useRef, useState } from 'react';
import Skeleton from 'smart-skeleton';

// Example 1: Product Card
export function ProductCard({ productId }) {
  const [loading, setLoading] = useState(true);
  const [product, setProduct] = useState(null);
  const cardRef = useRef(null);

  useEffect(() => {
    if (cardRef.current) {
      if (loading) {
        Skeleton.apply(cardRef.current, { 
          theme: 'light',
          randomize: true,
          deep: true,
          maxDepth: 5 
        });
      } else {
        Skeleton.remove(cardRef.current);
      }
    }
  }, [loading]);

  useEffect(() => {
    fetch(`/api/products/${productId}`)
      .then(res => res.json())
      .then(data => {
        setProduct(data);
        setLoading(false);
      });
  }, [productId]);

  return (
    <div ref={cardRef} className="card">
      {product && (
        <>
          <img src={product.image} alt={product.name} />
          <h3>{product.name}</h3>
          <p>{product.description}</p>
          <div className="price">${product.price}</div>
          <button>Add to Cart</button>
        </>
      )}
    </div>
  );
}

// Example 2: Nested Dashboard with Multiple Sections
export function Dashboard() {
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState(null);
  const dashboardRef = useRef(null);

  useEffect(() => {
    if (dashboardRef.current) {
      if (loading) {
        // Deep mode handles all nested children automatically
        Skeleton.apply(dashboardRef.current, { 
          theme: 'light',
          deep: true,
          maxDepth: 8, // Handles deeply nested structures
          randomize: true
        });
      } else {
        Skeleton.remove(dashboardRef.current);
      }
    }
  }, [loading]);

  useEffect(() => {
    Promise.all([
      fetch('/api/stats').then(r => r.json()),
      fetch('/api/chart-data').then(r => r.json()),
      fetch('/api/recent-orders').then(r => r.json())
    ]).then(([stats, chartData, orders]) => {
      setData({ stats, chartData, orders });
      setLoading(false);
    });
  }, []);

  return (
    <div ref={dashboardRef} className="dashboard">
      {/* Stats Grid - Nested flex container */}
      <div className="stats-grid">
        <div className="stat-card">
          <div className="stat-icon">📊</div>
          <div className="stat-content">
            <h3>Total Revenue</h3>
            <p className="stat-value">${data?.stats.revenue}</p>
            <span className="stat-change">+12% from last month</span>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon">👥</div>
          <div className="stat-content">
            <h3>Total Users</h3>
            <p className="stat-value">{data?.stats.users}</p>
            <span className="stat-change">+5% from last month</span>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon">📦</div>
          <div className="stat-content">
            <h3>Orders</h3>
            <p className="stat-value">{data?.stats.orders}</p>
            <span className="stat-change">+8% from last month</span>
          </div>
        </div>
      </div>

      {/* Chart Section - Complex nested structure */}
      <div className="chart-section">
        <div className="chart-header">
          <h2>Revenue Overview</h2>
          <div className="chart-controls">
            <button>Day</button>
            <button>Week</button>
            <button>Month</button>
          </div>
        </div>
        <div className="chart-container">
          {/* Chart would be rendered here */}
          <div className="chart-placeholder">Chart visualization</div>
        </div>
      </div>

      {/* Table Section - Deeply nested rows */}
      <div className="orders-section">
        <h2>Recent Orders</h2>
        <table className="orders-table">
          <thead>
            <tr>
              <th>Order ID</th>
              <th>Customer</th>
              <th>Amount</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {data?.orders.map(order => (
              <tr key={order.id}>
                <td>{order.id}</td>
                <td>
                  <div className="customer-cell">
                    <img src={order.customer.avatar} alt="" />
                    <span>{order.customer.name}</span>
                  </div>
                </td>
                <td>${order.amount}</td>
                <td>
                  <span className={`status status-${order.status}`}>
                    {order.status}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// examples/vue-example.vue
<template>
  <div class="app">
    <!-- Example 1: Simple Product Card -->
    <div ref="cardRef" class="card">
      <img :src="product.image" :alt="product.name" />
      <h3>{{ product.name }}</h3>
      <p>{{ product.description }}</p>
      <div class="price">${{ product.price }}</div>
      <button>Add to Cart</button>
    </div>

    <!-- Example 2: Deeply Nested User Profile -->
    <div ref="profileRef" class="profile">
      <div class="profile-header">
        <div class="profile-avatar">
          <img :src="user.avatar" :alt="user.name" />
          <span class="status-indicator online"></span>
        </div>
        <div class="profile-info">
          <h2>{{ user.name }}</h2>
          <p class="profile-title">{{ user.title }}</p>
          <div class="profile-badges">
            <span v-for="badge in user.badges" :key="badge" class="badge">
              {{ badge }}
            </span>
          </div>
        </div>
      </div>

      <div class="profile-stats">
        <div class="stat">
          <div class="stat-value">{{ user.stats.followers }}</div>
          <div class="stat-label">Followers</div>
        </div>
        <div class="stat">
          <div class="stat-value">{{ user.stats.following }}</div>
          <div class="stat-label">Following</div>
        </div>
        <div class="stat">
          <div class="stat-value">{{ user.stats.posts }}</div>
          <div class="stat-label">Posts</div>
        </div>
      </div>

      <div class="profile-content">
        <div class="profile-bio">
          <h3>About</h3>
          <p>{{ user.bio }}</p>
        </div>

        <div class="profile-links">
          <a v-for="link in user.links" :key="link.url" :href="link.url">
            <span class="link-icon">{{ link.icon }}</span>
            <span class="link-text">{{ link.text }}</span>
          </a>
        </div>
      </div>
    </div>

    <!-- Example 3: Complex Grid Layout -->
    <div ref="gridRef" class="products-grid">
      <div v-for="product in products" :key="product.id" class="product-card">
        <div class="product-image">
          <img :src="product.image" :alt="product.name" />
          <span class="product-badge">{{ product.badge }}</span>
        </div>
        <div class="product-details">
          <h4>{{ product.name }}</h4>
          <div class="product-rating">
            <span class="stars">★★★★★</span>
            <span class="reviews">({{ product.reviews }})</span>
          </div>
          <p class="product-description">{{ product.description }}</p>
          <div class="product-footer">
            <div class="product-price">
              <span class="current-price">${{ product.price }}</span>
              <span v-if="product.oldPrice" class="old-price">
                ${{ product.oldPrice }}
              </span>
            </div>
            <button class="add-to-cart">Add to Cart</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted, watch } from 'vue';
import Skeleton from 'smart-skeleton';

// Product Card Example
const cardRef = ref(null);
const cardLoading = ref(true);
const product = ref({});

// Profile Example  
const profileRef = ref(null);
const profileLoading = ref(true);
const user = ref({});

// Grid Example
const gridRef = ref(null);
const gridLoading = ref(true);
const products = ref([]);

// Watch loading states and apply/remove skeleton
watch(cardLoading, (loading) => {
  if (cardRef.value) {
    if (loading) {
      Skeleton.apply(cardRef.value, { 
        theme: 'light',
        randomize: true 
      });
    } else {
      Skeleton.remove(cardRef.value);
    }
  }
});

watch(profileLoading, (loading) => {
  if (profileRef.value) {
    if (loading) {
      // Deep mode handles all nested children
      Skeleton.apply(profileRef.value, { 
        theme: 'light',
        deep: true,
        maxDepth: 8,
        randomize: true 
      });
    } else {
      Skeleton.remove(profileRef.value);
    }
  }
});

watch(gridLoading, (loading) => {
  if (gridRef.value) {
    if (loading) {
      Skeleton.apply(gridRef.value, { 
        theme: 'light',
        deep: true,
        maxDepth: 6,
        randomize: true 
      });
    } else {
      Skeleton.remove(gridRef.value);
    }
  }
});

// Load data
onMounted(async () => {
  // Load product
  const productData = await fetch('/api/product/123').then(r => r.json());
  product.value = productData;
  cardLoading.value = false;

  // Load user profile
  const userData = await fetch('/api/user/profile').then(r => r.json());
  user.value = userData;
  profileLoading.value = false;

  // Load products grid
  const productsData = await fetch('/api/products').then(r => r.json());
  products.value = productsData;
  gridLoading.value = false;
});

// Cleanup
onUnmounted(() => {
  [cardRef, profileRef, gridRef].forEach(ref => {
    if (ref.value && Skeleton.isActive(ref.value)) {
      Skeleton.remove(ref.value);
    }
  });
});
</script>

<style scoped>
.products-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
  gap: 20px;
}

.profile {
  max-width: 600px;
  margin: 0 auto;
}

.profile-stats {
  display: flex;
  justify-content: space-around;
  padding: 20px 0;
}
</style>
